### ISSUE TITLE
Genomesize function, KeyError: 1

### ISSUE THREAD

**Issue by cjr41** [SLUR-m-Py/SLURPY#3]
Genomesize function is erroring. See below: 

```
$ ./SLURPY/peaks.py -r t2t --skip-dedup --merge
INFO: Making local directories.
INFO: Gathering chromosomes for processing.
INFO: Detected bwa index, skipping indexing.
INFO: Formatting jobs.
INFO: Skipping duplicate marking.
Traceback (most recent call last):
  File "/home/croth/.conda/envs/bioenv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./SLURPY/peaks.py", line 531, in <module>
    gsize = genomesize(g_size,reference_path,mito)
  File "/panfs/biopan04/4DGENOMESEQ/EPICPIPELINE/SLURPY/defaults.py", line 446, in genomesize
    genome_size = size_df[~(size_df[0].isin(makelist(mtDNA)))][1].sum()
  File "/home/croth/.conda/envs/bioenv/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/croth/.conda/envs/bioenv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 1

```

**Comment by cjr41** [comment]
The above error was corrected for in commit 67df8cb.
